### ISSUE TITLE
rename evaluator keywords in wiki

### ISSUE THREAD

**Issue by renezurbruegg** [ethz-asl/mav_active_3d_planning#39]
I think **EvaluatorUpdateNothing** and **EvaluatorResetTree** should be renamed to **UpdateNothing** and **ResetTree** in the wiki section ([ Evaluator Updaters](https://github.com/ethz-asl/mav_active_3d_planning/wiki/Code-Index#evaluator-updaters)).

Putting 
```  
evaluator_updater:
    type: "EvaluatorResetTree"
```
 in a .yaml config results in module not found errors.

**Comment by Schmluk** [comment]
The wiki has been updated, thanks for the catch!
