### ISSUE TITLE
Compilation failed

### ISSUE THREAD

**Issue by MaLin-art** [ethz-asl/mav_active_3d_planning#52]
My computer is Ubuntu18.04+ROS Melodic,According to the readme, at the "catkin build" step, it fails every time：
   [build] Summary: 25 of 52 packages succeeded
   [build] Ignored: 3 packages were skipped or are blacklisted
   [build] Warning: 6 packages succeeded with warnings 
   [build] Abandoned: 24 packages were abandoned
   [build] Failed: 3 packages failed.

**Comment by Schmluk** [comment]
Hi @MaLin-art 
Which packages fail to build? Can you paste the full compilation output?

**Comment by MaLin-art** [comment]
I am very happy to receive your email. I am a student from Hong Kong. I really appreciate your help. This is my compilation process. Thank you for your guidance!


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ethz-asl/mav_active_3d_planning"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月24日(星期天) 下午3:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ethz-asl/mav_active_3d_planning] Compilation failed (Issue #52)





 
Hi @MaLin-art
 Which packages fail to build? Can you paste the full compilation output?

**Comment by Schmluk** [comment]
Closed due to inactivity/missing info.
