### ISSUE TITLE
Resource files such as experimental scenes and ground truth point clouds do not exist

### ISSUE THREAD

**Issue by zcc0514** [ethz-asl/mav_active_3d_planning#59]
Hello!
First of all, thank you very much for your wonderful work! I have completed the installation process as described in your README.md, but I encountered problems in the download part of the relevant resources such as experimental scenes and ground truth point clouds. I clicked on the download page but the file was not found, so I would like to ask what is the reason why I can't download it? Or if you can send me the relevant resources, I would be very grateful. Looking forward to your kind reply!

![picture](https://github.com/ethz-asl/mav_active_3d_planning/assets/130729781/e73d989e-0e19-430c-b615-70388012d7c5)

**Comment by Schmluk** [comment]
Thanks for pointing this out! We have replaced the data repository with a [GDrive](https://drive.google.com/drive/folders/1Q0adl6CJURejYhSnc6fxctvg8YlKfRBY?usp=sharing) link!
