### ISSUE TITLE
How can I run exploration example?

### ISSUE THREAD

**Issue by yeop-giraffe** [ethz-asl/mav_active_3d_planning#67]
Thank you for sharing great works!
I am wondering if I can run exploration example. It seems there is only reconstruction example in your code.
Thank you in advance:)

**Comment by Schmluk** [comment]
You can use [this config](https://github.com/ethz-asl/mav_active_3d_planning/blob/master/active_3d_planning_app_reconstruction/cfg/planners/exploration_planner.yaml) to run the exploration planner by setting this in the launch file. Hope this helps!

**Comment by yeop-giraffe** [comment]
Thank you for a kind reply!
I will try it:)
