### ISSUE TITLE
catkin_make error

### ISSUE THREAD

**Issue by Willis814** [ethz-asl/mav_active_3d_planning#68]
CMake Error at /home/willis/UAVExplorer/catkin_ws/devel/share/yaml_cpp_catkin/cmake/yaml_cpp_catkinConfig.cmake:173 (message):
  Project 'mav_trajectory_generation' tried to find library 'yaml-cpp0.5'.
  The library is neither a target nor built/installed properly.  Did you
  compile project 'yaml_cpp_catkin'? Did you find_package() it before the
  subdirectory containing its code is included?
Call Stack (most recent call first):
  mav_trajectory_generation/mav_trajectory_generation/CMakeLists.txt:12 (find_package)

Is the error due to my yaml-cpp is 0.6.2 ? Or is there something wrong with the build order? My system is ubuntu 20.04 and ros version is Noetic.

**Comment by mikedh-avia** [comment]
Have you figured it out? Would you mind sharing how? Thanks.
